//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GreetingServiceConsoleClient.Greetings {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GreetingRequest", Namespace="http://conestogac.on.ca/schemas/2023/09/greetings")]
    [System.SerializableAttribute()]
    public partial class GreetingRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RecipientField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Recipient {
            get {
                return this.RecipientField;
            }
            set {
                if ((object.ReferenceEquals(this.RecipientField, value) != true)) {
                    this.RecipientField = value;
                    this.RaisePropertyChanged("Recipient");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GreetingResponse", Namespace="http://conestogac.on.ca/schemas/2023/09/greetings")]
    [System.SerializableAttribute()]
    public partial class GreetingResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string GreetingField;
        
        private string TimeOfDayField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Greeting {
            get {
                return this.GreetingField;
            }
            set {
                if ((object.ReferenceEquals(this.GreetingField, value) != true)) {
                    this.GreetingField = value;
                    this.RaisePropertyChanged("Greeting");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string TimeOfDay {
            get {
                return this.TimeOfDayField;
            }
            set {
                if ((object.ReferenceEquals(this.TimeOfDayField, value) != true)) {
                    this.TimeOfDayField = value;
                    this.RaisePropertyChanged("TimeOfDay");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Greetings.IGreetingService")]
    public interface IGreetingService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGreetingService/Greet", ReplyAction="http://tempuri.org/IGreetingService/GreetResponse")]
        GreetingServiceConsoleClient.Greetings.GreetingResponse Greet(GreetingServiceConsoleClient.Greetings.GreetingRequest greatingRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGreetingService/Greet", ReplyAction="http://tempuri.org/IGreetingService/GreetResponse")]
        System.Threading.Tasks.Task<GreetingServiceConsoleClient.Greetings.GreetingResponse> GreetAsync(GreetingServiceConsoleClient.Greetings.GreetingRequest greatingRequest);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGreetingServiceChannel : GreetingServiceConsoleClient.Greetings.IGreetingService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GreetingServiceClient : System.ServiceModel.ClientBase<GreetingServiceConsoleClient.Greetings.IGreetingService>, GreetingServiceConsoleClient.Greetings.IGreetingService {
        
        public GreetingServiceClient() {
        }
        
        public GreetingServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GreetingServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GreetingServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GreetingServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public GreetingServiceConsoleClient.Greetings.GreetingResponse Greet(GreetingServiceConsoleClient.Greetings.GreetingRequest greatingRequest) {
            return base.Channel.Greet(greatingRequest);
        }
        
        public System.Threading.Tasks.Task<GreetingServiceConsoleClient.Greetings.GreetingResponse> GreetAsync(GreetingServiceConsoleClient.Greetings.GreetingRequest greatingRequest) {
            return base.Channel.GreetAsync(greatingRequest);
        }
    }
}
